# your domain
domain: 192.168.1.104:8080
#domain: 127.0.0.1

# database dsn(postgresql)
# 暂不支持远程数据库，留空以启用本地数据库默认连接参数
database_url: ""

# cloudflare api
cf_email: ""
cf_key: ""

# source definition file
source-files:
  # use local file
  - E:\proxypool038-master\config\source.yaml
  # use web file
  - https://raw.githubusercontent.com/Alex950808/proxypool038/master/config/source.yaml
  - https://raw.githubusercontent.com/wishcaiji/proxypool/master/config/source.yaml
  - https://raw.githubusercontent.com/money-fly/proxypool/master/config/source.yaml
